# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 117d0d4c496595305ebc55d5e726bb0a908eb23e16e3d9eb6d3ceb837ff3c772a4cab73f87f24cf1422cd618dfcd26d1477f1c3c2182509116c36e56ff91393b

test:
  secret_key_base: db56d7a9f54ebc5372c0fb743c20c30dc26fbf8135a0732600011a89f6aacd0e5b0aa55431ddb790fe3e8aaf5b2e42fab1d6805d9d972af9b0f0c8d5afe55b0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
